### ISSUE TITLE
Làm sao để crawler dữ liệu ? 

### ISSUE THREAD

**Issue by kingkong135** [CTU-LinguTechies/VN-Law-Advisor#76]
Trong phần readme, các bạn có hướng dẫn tạo 2 file json từ file jsonData.json gốc để tạo ra các file khác. Nhưng mình không thấy code phần đó ?

**Comment by TranHuyZIT** [comment]
Hi bạn, các file JSON gốc bạn có thể tìm thấy tại trang [Bộ Pháp Điển](https://phapdien.moj.gov.vn/Pages/chi-tiet-bo-phap-dien.aspx) nhé, các file này sẽ chứa các biến js, bạn có thể lấy nó sang các file khác nhe.
